name: "\U0001F58B Feature / Enhancement proposal"
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Describe the project you are working on
      description: >
        This is important to know the *context* in which the feature is being proposed.
        Features used in real-world projects are more likely to be added.
      placeholder: Example - "A dialogue system using this plugin"

  - type: textarea
    attributes:
      label: >
        Describe the feature / enhancement and how it helps to overcome the problem or limitation
      placeholder: >
        Example - "Add documentation to the plugin to know how to use it. 
        Document things like how the timeline works or what does its classes and what are their properties"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Adittional information
      description: >
        If you want to add more information related to this proposal, add it here. 
        Things like mockups, videos, detailed step to step to integrate the request,
        how your proposal will work or anything that you want.
